// Traductions FR / EN / AR avec support RTL
export const translations = {
  fr:{'nav.catalog':'Catalogue','nav.how':'Fonctionnement','nav.contact':'Contact','hero.eyebrow':'Livraison à Djibouti-Ville','hero.title':'Vos courses livrées vite, simplement, depuis WhatsApp.','hero.subtitle':'AHADO EXPRESS aide les familles, boutiques, restaurants, hôtels et cafétérias à commander leurs produits essentiels sans perdre de temps.','hero.cta':'Commander maintenant','hero.districts':'quartiers desservis','hero.products':'produits disponibles','how.title':'Comment ça marche ?','how.oneTitle':'Choisissez','how.oneText':'Ajoutez les produits au panier.','how.twoTitle':'Validez','how.twoText':'Indiquez téléphone, quartier, adresse et paiement.','how.threeTitle':'Recevez','how.threeText':'La commande part vers WhatsApp AHADO EXPRESS.','catalog.eyebrow':'Catalogue','catalog.title':'Produits populaires et essentiels','catalog.searchLabel':'Rechercher','catalog.count':'produits disponibles','cart.title':'Votre panier','cart.freeDelivery':'Livraison gratuite à 5 000 FDJ','cart.upsell':'Souvent commandé avec','cart.checkout':'Valider la commande','checkout.title':'Finaliser','checkout.name':'Nom','checkout.phone':'Téléphone','checkout.district':'Quartier','checkout.address':'Adresse précise','checkout.payment':'Paiement','checkout.send':'Envoyer sur WhatsApp','footer.text':'Livraison de courses à Djibouti-Ville.','footer.rights':'Tous droits réservés.'},
  en:{'nav.catalog':'Catalog','nav.how':'How it works','nav.contact':'Contact','hero.eyebrow':'Delivery in Djibouti City','hero.title':'Groceries delivered fast and easily from WhatsApp.','hero.subtitle':'AHADO EXPRESS helps families, shops, restaurants, hotels and cafés order essential products without wasting time.','hero.cta':'Order now','hero.districts':'served districts','hero.products':'available products','how.title':'How does it work?','how.oneTitle':'Choose','how.oneText':'Add products to your cart.','how.twoTitle':'Confirm','how.twoText':'Enter phone, district, address and payment method.','how.threeTitle':'Receive','how.threeText':'The order is sent to AHADO EXPRESS on WhatsApp.','catalog.eyebrow':'Catalog','catalog.title':'Popular and essential products','catalog.searchLabel':'Search','catalog.count':'available products','cart.title':'Your cart','cart.freeDelivery':'Free delivery from 5,000 FDJ','cart.upsell':'Frequently ordered with','cart.checkout':'Checkout','checkout.title':'Checkout','checkout.name':'Name','checkout.phone':'Phone','checkout.district':'District','checkout.address':'Precise address','checkout.payment':'Payment','checkout.send':'Send on WhatsApp','footer.text':'Grocery delivery in Djibouti City.','footer.rights':'All rights reserved.'},
  ar:{'nav.catalog':'المنتجات','nav.how':'طريقة الطلب','nav.contact':'التواصل','hero.eyebrow':'توصيل داخل مدينة جيبوتي','hero.title':'مشترياتك تصل بسرعة وبسهولة عبر واتساب.','hero.subtitle':'AHADO EXPRESS يساعد العائلات والمتاجر الصغيرة والمطاعم والفنادق والمقاهي على طلب المنتجات الأساسية دون ضياع الوقت.','hero.cta':'اطلب الآن','hero.districts':'أحياء نخدمها','hero.products':'منتج متوفر','how.title':'كيف يعمل؟','how.oneTitle':'اختر','how.oneText':'أضف المنتجات إلى السلة.','how.twoTitle':'أكد','how.twoText':'أدخل الهاتف والحي والعنوان وطريقة الدفع.','how.threeTitle':'استلم','how.threeText':'يتم إرسال الطلب إلى واتساب AHADO EXPRESS.','catalog.eyebrow':'الكتالوج','catalog.title':'منتجات أساسية وشائعة','catalog.searchLabel':'بحث','catalog.count':'منتج متوفر','cart.title':'سلتك','cart.freeDelivery':'توصيل مجاني ابتداءً من 5,000 فرنك','cart.upsell':'يُطلب غالبًا مع','cart.checkout':'تأكيد الطلب','checkout.title':'إتمام الطلب','checkout.name':'الاسم','checkout.phone':'الهاتف','checkout.district':'الحي','checkout.address':'العنوان التفصيلي','checkout.payment':'الدفع','checkout.send':'إرسال عبر واتساب','footer.text':'توصيل مشتريات داخل مدينة جيبوتي.','footer.rights':'جميع الحقوق محفوظة.'}
};
export function applyI18n(lang='fr'){
  const safeLang = translations[lang] ? lang : 'fr';
  document.documentElement.lang = safeLang;
  document.documentElement.dir = safeLang === 'ar' ? 'rtl' : 'ltr';
  document.body?.setAttribute('dir', document.documentElement.dir);
  document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent = translations[safeLang][el.dataset.i18n] || el.textContent;});
  localStorage.setItem('ahado_lang', safeLang);
}
export function getLang(){return new URLSearchParams(location.search).get('lang') || localStorage.getItem('ahado_lang') || 'fr';}
